[subnet-visualizer] Allow to click on used ip to change them
openwisp/django-ipam pull request #103
Opened 2020-03-01 22:52 UTC by nepython

Closes #101

2020-03-02 00:28 UTC, nepython commented
@nemesisdesign, can you please review this :smile:

2020-03-02 10:29 UTC, atb00ker reviewed
Is it me or does it get stuck on "Closing popup" on firefox when I try to change an existing IP's information?

2020-03-02 10:38 UTC, atb00ker reviewed
Also, `?_to_field=id&_popup=1&ip_address=<ip>&subnet=<uuid>` doesn't really serve us, can it be removed from the URL without adding a lot more code? (otherwise, it's all the same)

Edit: `_popup=1&amp;` might be useful! :smile:

2020-03-02 10:48 UTC, atb00ker commented on django_ipam/base/admin.py
> +            ip_uuid[ip_addr] = Ip[0:8] + '-' + Ip[8:12] + '-' + Ip[12:16] + '-' + Ip[16:20] + '-' + Ip[20:]
```suggestion
            ip_uuid[ip_addr] = {0}-{1}-{2}-{3}.format(Ip[0:8], Ip[8:12],  Ip[12:16], Ip[16:20], Ip[20:])
```

2020-03-02 10:48 UTC, atb00ker commented on django_ipam/base/admin.py
> +        ip_id_list = IpAddress.objects.annotate(str_id=Cast('id', output_field=TextField())) \
Can't we filter for current subnet?

2020-03-02 13:17 UTC, nepython commented
> Is it me or does it get stuck on "Closing popup" on firefox when I try to change an existing IP's information?

Let me check this out.

2020-03-07 14:29 UTC, nepython commented
@atb00ker, I have applied necessary changes suggesyed by you and taken care of the popup closing issue, though it seems I will have to add new test cases for the changes. Extremely sorry for replying so late, I had my exams going on so couldn't put in much time😅.

2020-03-07 16:13 UTC, nemesifier reviewed
@nepython can you make sure the test coverage does not decrease please?

2020-03-07 16:20 UTC, nepython commented
Sure, I am making new test cases for the same.

2020-03-07 22:27 UTC, nepython commented
@nemesisdesign, can you please review this?:smile:

2020-03-09 10:26 UTC, atb00ker approved these changes
LGTM, thanks! :+1:

2020-03-09 10:27 UTC, atb00ker commented
P.S: f-strings joined the party in Python 3.6 not 3.7 as I thought earlier, so I think we can use it everywhere! :smile:

2020-03-11 03:41 UTC, nemesifier requested changes
Great, please also remove

```css
cursor: default;
```

From `.subnet-visual a.used` in the CSS so the cursor shows the normal icon when hovering on the links.

2020-03-11 07:43 UTC, nepython commented
Done :smiley:

2020-03-11 22:55 UTC, nemesifier approved these changes

2020-03-11 22:57 UTC, nemesifier reviewed
Great, could you please rebase on the current master and resolve the conflict?

2020-03-12 08:35 UTC, nepython commented
Done

2020-03-13 21:25 UTC, nepython commented
@nemesisdesign, can you please review this :smiley:

2020-03-13 22:33 UTC, nemesifier approved these changes
Great work @nepython. Now the goal should be that in your next patches you can get to this point with a lot less interaction and review on our side. That's why you should keep training.

2020-03-13 22:33 UTC, merged

2020-03-14 03:19 UTC, nepython commented
> Great work @nepython. Now the goal should be that in your next patches you can get to this point with a lot less interaction and review on our side. That's why you should keep training.

Sure, @nemesisdesign will try to achieve that
:)