[Models] Upgrading models
openwisp/django-ipam pull request #11
Opened 2018-05-18 08:13 UTC by anurag-ks

Implements and closes #7

2018-05-18 08:16 UTC, anurag-ks commented
@nemesisdesign I am try to finish up with the model structure. Right now I am analyzing the phpipam database scheme and trying to replicate it over here. It's kinda taking time because I have figure out what is perfect field type for each attribute. Also some more tests are pending.

2018-05-22 08:18 UTC, nemesifier requested changes
Please add the following validation checks:

- check if ip address is really comprised in the specified subnet, otherwise raise `ValidationError`
- check if ip address is already taken and if yes raise `ValidationError` (don't make it `unique` yet..)
- if master subnet is specified, check current subnet is really comprised in it, otherwise raise `ValidationError`

Also, please do the following:

- add an index on the `ip_address` field
- add some basic tests for ipv6 addresses and subnets

2018-05-22 08:18 UTC, nemesifier commented on django_ipam/base/models.py
> +    is_gateway = models.BooleanField(default=False)
remove this, we may add it back later if and when we need it to implement an actual feature

2018-05-22 08:18 UTC, nemesifier commented on django_ipam/base/models.py
> +    used = models.BooleanField(default=False)
remove this, we may add it back later if we need it

2018-05-22 08:18 UTC, nemesifier commented on django_ipam/base/models.py
> +    mac_address = models.CharField(max_length=12, blank=True)
if we add it we need to validate it's really a mac address, but we have a such a field in[ django-netjsonconfig](https://github.com/openwisp/django-netjsonconfig/blob/master/django_netjsonconfig/base/device.py#L15-L19) and I don't want to make it redundant here. If an user of this app will need it they can extend the app and add it, but we as openwisp do not need this here now, therefore please remove it

2018-05-22 08:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +    netmask = models.CharField(max_length=12, blank=True)
I don't see the utility of having these two fields:

- `host` I think refers to hostname, we have this information in django-netjsonconfig as well
- `netmask`: the netmask is basically the subnet, I don't understand: why we need to have this information stored twice?

2018-05-22 08:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +    ip_request = models.BooleanField(default=False)
what's this for? Can we add this field only when we are going to actually use it for something? This kind of unused code clutters my mind.

2018-05-22 08:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +    subnet = NetworkField(default="10.0.0.0/24")
is this field indexed? Make sure it is

2018-05-25 09:18 UTC, nemesifier requested changes
See my comments

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +        self.full_clean()
Remove this, never ever do this. In django, model validation is performed explicitly. If you add this here, in many other parts django will execute the validation twice

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +    def clean_fields(self, exclude=None):
use `clean`

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +            if(ip_network(self.subnet).overlaps(subnet["subnet"])):
it should be `if ip_network(self.subnet).overlaps(subnet["subnet"]):`

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +            if(ip_address(self.ip_address) not in self.subnet.subnet):
convert to `if self.subnet and ip_address(self.ip_address) not in self.subnet.subnet:`

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +            if(ip_address(self.ip_address) == ip_address(ipaddr["ip_address"])):
`if ip_address(self.ip_address) == ip_address(ipaddr["ip_address"]):`

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/base/models.py
> +        self.full_clean()
remove

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/tests/base/test_models.py
> +            failed = False
check the exception being thrown has something you expect in it, eg: https://github.com/openwisp/openwisp-controller/blob/connections/openwisp_controller/connection/tests/test_models.py#L105

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/tests/base/test_models.py
> +        if(failed):
don't use parenthesis

2018-05-25 09:18 UTC, nemesisdesign commented on django_ipam/tests/base/test_models.py
> +            failed = False
check the exception being thrown has something you expect in it, eg: https://github.com/openwisp/openwisp-controller/blob/connections/openwisp_controller/connection/tests/test_models.py#L105

2018-05-28 09:33 UTC, nemesifier reviewed
See my comments

2018-05-28 09:33 UTC, nemesisdesign commented on django_ipam/base/models.py
>      subnet = models.ForeignKey(swapper.get_model_name("django_ipam", "Subnet"),
one queston: why this field can be left blank? Shouldn't this be mandatory?

2018-05-28 09:33 UTC, nemesisdesign commented on django_ipam/base/models.py
> +        if self.ip_address:
I think you can remove this if because `ip_address` is mandatory and the validation will fail earlier if that's blank

2018-05-28 09:33 UTC, nemesisdesign commented on django_ipam/base/models.py
> +            if self.subnet:
if this field becomes mandatory as I think it should you can remove this if as well

2018-05-28 13:29 UTC, nemesifier approved these changes
:+1: good!

2018-05-28 13:31 UTC, nemesisdesign commented on django_ipam/base/models.py
> +                               on_delete=models.CASCADE, null=True)
remove `null=True` from here as well (update the migrations) and then we are good

2018-05-28 14:24 UTC, merged