[subnet] Freespace display for Subnet
openwisp/django-ipam pull request #15
Opened 2018-05-28 16:23 UTC by anurag-ks

Implements and closes #12

2018-05-28 18:53 UTC, anurag-ks commented
![screenshot-2018-5-28 change subnet openwisp2 admin](https://user-images.githubusercontent.com/3973075/40626477-6d3c2a72-62d6-11e8-8396-d12fd2ff14a6.png)

2018-06-01 06:23 UTC, rohithasrk approved these changes
Looks good to me. Check some comments. Final review by @nemesisdesign though.

2018-06-01 06:23 UTC, rohithasrk commented on django_ipam/base/admin.py
> +        instance = swapper.load_model("django_ipam", "Subnet").objects.get(pk=object_id)
Why don't you reference `Subnet = swapper.load_model('django_ipam', 'Subnet') instead of calling swapper multiple times?

2018-06-01 06:23 UTC, rohithasrk commented on django_ipam/base/admin.py
> +        extra_context['values'] = values
Maybe also try `extra_context.update({'labels': labels, 'values': values})`

2018-06-06 18:36 UTC, anurag-ks commented
@nemesisdesign I have also added the visual display for the subnet in this PR as well, the functionality is done, I am improving the UI for now.

2018-06-11 09:53 UTC, nemesifier requested changes
Good progress!

- `plotly-latest.min.js` is not a good file name because in a few months our version won't be "latest" anymore. Use `plotly.min.js`

See my other inline comments.

I'm going to test the admin now so expect more comments in a bit.

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +        total = [x for x in instance.subnet.hosts()]
could you use something more meaningful than `x` please?

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +        if request.POST.get("_popup"):
could you add some comments in the code on why this is necessary? Never seen such a thing.

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +      <div style="padding:10px">
we should really use a CSS file instead of inline CSS, this applies to all the other inline styling as well

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +                  {{i}}
please use something more meaningful than `i`
for template variables, for consistency with the rest of the openwisp2 modules, please always use this style: `{{ variable_name }}` (add spaces between brackets)

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +                <a href="/admin/django_ipam/ipaddress/add/?_to_field=id&_popup=1&ip_address={{i}}" onclick='return showAddAnotherPopup(this);'>
see github highlight those `&` in red? Try rewriting `&` as `&amp;` (correct HTML entity code for ampersands) and check if the link still works, should work

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +      }];
improve indentation for readability purposes, eg:

```javascript
var data = [
  {
    values: {{ values|safe }},
    labels: {{ labels|safe }},
    type: 'pie',
    hoverinfo: 'label+value',
    textinfo: 'value',
    hole: .4
  }
];
```

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +    var layout = {
group `var` definitions eg:

```javascript
var data = [],
    layout = {}
```

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +        extra_context.update({'labels': labels,
you are initializing a new dict and then updating it, why is that? Wouldn't make more sense to define the dict directly without using `update`?

2018-06-11 09:53 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +      </div>
rewrite these 2 lines as ` <div id="graph"></div>` to keep it more compact

2018-06-11 09:59 UTC, nemesifier requested changes
since we are adding JS code, we should add these JS style checks to the build as well:

- https://github.com/openwisp/django-freeradius/blob/master/.jslintrc
- https://github.com/openwisp/django-freeradius/blob/master/.travis.yml#L41-L42

2018-06-11 11:07 UTC, nemesifier requested changes
## Admin 

- created and modified should always appear as last and as readonly, use this mixin: https://github.com/openwisp/openwisp-utils/blob/master/openwisp_utils/admin.py#L91-L98
- add a `help_text` to the subnet field in subnet add/change form, assume also less tech-savy users may use this module, provide an example subnet in the help text
- why there's a default value here? https://github.com/openwisp/django-ipam/blob/master/django_ipam/base/models.py#L14; I think no default value should be provided here
- in the PIE chart, I see numbers in black color which are not very readable, could you do the following?
  - make them bold
  - use a contrasting background color, for example, white foreground on dark background (eg: `rgba(0, 0, 0, 0.65)`)
- regarding the list of ip addresses, please add a CSS file so I can add some styling that will make it look a bit better

## IPv6

- what happens when using IPv6? Have you tested this use case at all?
- I can't seem to be able to add this subnet: `fdb6:21b:a477::9f7/64`
- I am afraid the list of available/free ip addresses will become huge, we'll need to test this use case and find a solution to make it work decently with IPv6 as well

2018-06-13 08:21 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +    data = [{
should be:
```
data = [
  {
# ...
```

2018-06-13 08:52 UTC, nemesifier requested changes
Good progress.

A few more improvements are needed:

- try editing an existing ip address, then click on edit icon on subnet field, a popup will openup.. the graph and address list look a bit weird, can you find a way to disable those when opening in popup mode?
- the pie chart is not shown in ipv6
- in ipv6, the address list is hidden as we agreed, but I can see the heading `Used IP address` which I think should be hidden
- add django-extensions to `requirements-test.txt` and to  `settings.INSTALLED_APPS` as we discussed in chat, this should be quick, ensure the command `./manage.py shell_plus` works

2018-06-13 08:52 UTC, nemesisdesign commented on django_ipam/templates/admin/django-ipam/change_form.html
> +        labels: {{labels|safe}},
as explained previously, please use the format ``{{ labels|safe }}`` (space between brackets)

2018-06-13 08:52 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +        '''
change to the following for consistency with other ow2 modules:

```
"""
Custom reponse to dismiss an add form popup for IP address.
"""
```

2018-06-13 08:52 UTC, nemesisdesign commented on django_ipam/base/models.py
> +    subnet = NetworkField(help_text=HELP_TEXT, db_index=True)
Good improvement, let's improve it even more, do this and get rid of the `HELP_TEXT` variable above (for consistency with the other ow2 modules):

```python
class AbstractSubnet(TimeStampedEditableModel):
    subnet = NetworkField(db_index=True,
                          help_text=_('Subnet in CIDR notation, eg: "10.0.0.0/24" '
                                      'for IPv4 and "fdb6:21b:a477::9f7/64" for IPv6'))
```

2018-06-13 09:27 UTC, nemesifier reviewed
See what I changed in my additional commits

2018-06-13 12:55 UTC, nemesisdesign commented on django_ipam/base/models.py
> +                if ip_network(self.subnet).overlaps(subnet["subnet"]):
please rewrite this in a single line:

```
if self.id != subnet["id"] and if ip_network(self.subnet).overlaps(subnet["subnet"]):
    # ...
```

2018-06-13 12:58 UTC, nemesifier requested changes

2018-06-13 12:58 UTC, nemesisdesign commented on django_ipam/base/models.py
> +            if self.id != subnet["id"]:
I find this weird.

A better alternative would be:

```
if self.id == subnet["id"]:
    continue
if ip_network(self.subnet).overlaps(subnet["subnet"]):
    pass
```

or also a single `if` statement

2018-06-13 12:58 UTC, nemesisdesign commented on django_ipam/base/models.py
> +                if ip_address(self.ip_address) == ip_address(ipaddr["ip_address"]):
same here, don't use nested ifs with a single condition please

2018-06-13 13:11 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +            available = 2**(128-instance.subnet.prefixlen) - used
I prefer with spaces:
```
available = 2 ** (128 - instance.subnet.prefixlen ) - used
```

2018-06-14 07:18 UTC, nemesifier approved these changes
:+1:

2018-06-14 07:18 UTC, merged