[api] RESTful api for Subnet and IpAddress
openwisp/django-ipam pull request #30
Opened 2018-07-06 15:34 UTC by anurag-ks

Implements and closes #10 

This is a WIP PR, I wanted to confirm all the endpoints that we would be implementing in django-ipam.

2018-07-09 11:23 UTC, nemesifier requested changes
@anurag-ks where are the tests and the reusable views?

2018-07-09 11:31 UTC, anurag-ks commented
@nemesisdesign I first wanted to confirm these endpoints are okay or not and then move on to writing tests for these views.

2018-07-09 11:41 UTC, nemesisdesign commented
@anurag-ks you have to implement CRUD operations as described in http://openwisp.org/gsoc/ideas-2018.html

2018-07-10 08:51 UTC, nemesifier requested changes
Good progress. See below.

- could you avoid `_create_subnet(dict(subnet="10.0.0.0/24"))` in favour of `_create_subnet(subnet="10.0.0.0/24")`? See how is done here: https://github.com/openwisp/openwisp-controller/blob/connections/openwisp_controller/connection/tests/base.py#L18-L30
- please add tests for the sample app as well to ensure the generic views work with custom models as well.
- please add a test for the case in which a user is not logged-in
- see my inline comments as well

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(response.status_code, 200)
perform a basic check of the contents also please

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(len(Subnet.objects.all()), 0)
use `Subnet.objects.count()` which is faster

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(str(IpAddress.objects.first()), '10.0.0.2')
access the `ip_address` attribute because `str()` representation may be changed and would break this test

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(response.status_code, 200)
perform a basic check of the contents please

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(len(IpAddress.objects.all()), 0)
use count as indicated in a previous comment

2018-07-10 08:51 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertEqual(response.status_code, 200)
please perform a basic check of the contents too

2018-07-10 15:19 UTC, nemesifier requested changes
some minor improvements to the tests are needed, see see my comments

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/api/serializers.py
> +        fields = '__all__'
I think you should make some fields readonly like `created` and `modified`

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/api/serializers.py
> +        fields = '__all__'
I think you should make some fields readonly like `created` and `modified`

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertContains(response, str(subnet_id))
this is not good enough, you should check one of the attributes of the JSON response in `response.data`.

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertContains(response, '10.0.0.1')
same here

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        }
write this as one line

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +        self.assertContains(response, '10.0.0.2')
same here

2018-07-10 15:19 UTC, nemesisdesign commented on django_ipam/tests/base/test_api.py
> +                                    data=json.dumps(data),
simply use `data=json.dumps({}),` and remove the definition of `data`

2018-07-10 16:16 UTC, nemesifier reviewed
Looks good, only docs are missing:

- explain how to use new api methods
- remember to explain how to authenticate
- explain how to extend the views, take inspiration from the docs of django-netjsongraph

2018-07-11 10:01 UTC, nemesifier requested changes
Some improvements needed, see below.

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +    <api-url> -H 'Cookie: csrftoken=<csrftoken>; sessionid=<session-id>'
no man, this is not good. the API must work without the CSRF mechanism, this is not a webpage.

Ensure the API works without the CSRF token

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +++++
should be `+++`

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +An api enpoint to retrieve or create IP addresses under a specific subnet
always leave a blank line after the title

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Returns the list of IP addresses under a particular subnet.
always leave a blank line after the title

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Create an Ip Address record
always leave a blank line after the title

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Create an Ip Address record
should be `Create a new ``IpAddress``.`

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +An api endpoint to create or retrieve the list of subnet instances
Add final dot

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Returns the list of Subnet instances
add final dot, add double quotes to ``Subnet``, leave blank line after title, the plus signs should be only 3: `+++`

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Create a new subnet record
change to `Create a new ``Subnet``.` leave blank line after title

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +An api endpoint for retrieving, updating or deleting a subnet instance.
leave blank line after title

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Delete a subnet instance
Leave blank line after title, add final dot, double quote ``Subnet`` (model class name).

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Update details of a subnet instance
same here

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Get details of an IP address instance
same here

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Delete an IP address instance
same

2018-07-11 10:01 UTC, nemesisdesign commented on README.rst
> +Update details of an IP address instance
same

2018-07-11 13:23 UTC, nemesifier approved these changes
:+1:

2018-07-11 13:23 UTC, merged