Added ci check for migrations
openwisp/django-ipam pull request #57
Opened 2018-11-13 17:42 UTC by EdgeKing810

Task: https://codein.withgoogle.com/tasks/4650995146555392/?sp-organization=4514829432782848&sp-is_beginner=False
Not yet claimed due to another task where I need some help: https://github.com/openwisp/OpenWISP-Website/pull/21

I think I wrongly wrote the code in the "runcheckmigration" file tho...

2018-11-13 17:57 UTC, atb00ker reviewed
Hello. Quick review:

1. No empty line at the end of the file. (You can setup your editor to this for you.)
2. Did you checkout why Travis failed? It looks the file did not have the permission to execute, please add that permission.
3. Commit Message, again. It will have `[ci]` tag in this pull request.

(I didn't find a particular reason you asked for a review here, do you have a question in mind? :smile: )

2018-11-13 18:28 UTC, EdgeKing810 commented
Oh okay, I did all that... and I didn't know the file needed to be marked as executable. Thanks for helping me out on this one!

2018-11-13 18:41 UTC, EdgeKing810 commented
Build's successful! Thanks @atb00ker !
And I needed to add an empty line to the .travis.yml file else it wasn't running, Idk why.

2018-11-16 16:00 UTC, nemesifier requested changes

2018-11-16 16:00 UTC, nemesisdesign commented on .travis.yml
> +  - coveralls
missing new line

2018-11-16 16:00 UTC, nemesisdesign commented on requirements-test.txt
> +openwisp-utils
`openwisp-utils>=0.2.1`

2018-11-16 16:00 UTC, nemesisdesign commented on runcheckmigration
> + checkmigrations --migrations-to-ignore 3 \
remove `--migrations-to-ignore 3 \`

2018-11-16 16:00 UTC, nemesisdesign commented on runcheckmigration
> + checkmigrations --migrations-to-ignore 2 \
same here

2018-11-16 17:47 UTC, EdgeKing810 commented
I had based myself on the PR you validated for cking some while ago before you told me and already did the changes to spare you of commenting again... Thanks for checking this PR too tho!

2018-11-16 20:17 UTC, atb00ker approved these changes

2018-11-18 11:40 UTC, nemesifier requested changes

2018-11-18 11:40 UTC, nemesisdesign commented on runcheckmigration
> + checkmigrations --migration-path ./tests/sample_ipam/migrations/ || exit 1
it would have been perfect this time if it wasn't for the whitespace in the beginning of these previous lines, please remove that

2018-11-18 15:54 UTC, nemesifier approved these changes

2018-11-18 15:55 UTC, merged