[enchancement] Implemented subnet hierarchical view
openwisp/django-ipam pull request #73
Opened 2019-02-03 18:15 UTC by atb00ker

GUI change, hence screenshots included:

**IPv4 view:**
![ipv4_shot](https://user-images.githubusercontent.com/24985760/52180543-9e7a1e80-280d-11e9-9a88-c439b37b2e86.png)

**IPv6 view:**
![ipv6_shot](https://user-images.githubusercontent.com/24985760/52180544-9e7a1e80-280d-11e9-946f-3e89fd578ae7.png)

2019-02-05 00:25 UTC, nemesifier reviewed
not sure what is happening with travis! :disappointed: 

I tested the changes and added a few comments below.

2019-02-05 00:25 UTC, nemesifier commented on django_ipam/static/django-ipam/js/subnets.js
> +        console.log(data.selected);
is this a leftover?

2019-02-05 00:25 UTC, nemesifier commented on django_ipam/templates/admin/django-ipam/subnet/change_form.html
> +      var subnet_node = document.createTextNode(subnet_tree[item]["subnet_tree_item"]);
try to use a single `var` statement, eg:

```javascript
var var1 = 1,
    var2 = 2;
```

2019-02-05 00:25 UTC, nemesifier commented on django_ipam/base/admin.py
> +              )
this parenthesis on its own line hurts my eyes :joy_cat:

2019-02-05 00:25 UTC, nemesifier commented on django_ipam/base/admin.py
> +            instance_root = Subnet.objects.get(subnet=instance_root.master_subnet)
this can fail, eg:

```
MultipleObjectsReturned at /admin/django_ipam/subnet/a6162727-b215-474e-9562-90237654b3cf/change/
get() returned more than one Subnet -- it returned 2!
```

2019-02-09 20:22 UTC, atb00ker commented on django_ipam/base/admin.py
> +            instance_root = Subnet.objects.get(subnet=instance_root.master_subnet)
Can you please help me reproduce this one?
The subnet objects i am creating are working. What options do i need to create an object which will fail here.

2019-02-09 20:22 UTC, atb00ker commented on django_ipam/static/django-ipam/js/subnets.js
> +        console.log(data.selected);
Yes, thanks for pointing this one out. :smile:

2019-02-09 20:33 UTC, atb00ker commented
> not sure what is happening with travis!

I approached the travis community since i couldn't solve it. I was recommended to clean cache and run again.
So far no luck, i will post update if there is any further news.

2019-04-02 01:21 UTC, nemesisdesign commented on django_ipam/base/admin.py
> +            instance_root = Subnet.objects.get(subnet=instance_root.master_subnet)
try creating a master subnet, then create 2 different child subnets on that master subnet

2019-04-02 14:28 UTC, nemesifier reviewed
the problem with the segmentation fault in the build has now gone away, but a test is failing in the sample_app.

```
======================================================================
ERROR: test_hierarchy_tree (sample_ipam.tests.TestAdmin)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/openwisp/django-ipam/django_ipam/tests/base/test_admin.py", line 212, in test_hierarchy_tree
    subnet_child = self._create_subnet(subnet='11.0.0.0/25', name='Child#1', master_subnet=subnet_root)
  File "/home/travis/build/openwisp/django-ipam/django_ipam/tests/__init__.py", line 31, in _create_subnet
    instance.full_clean()
  File "/home/travis/virtualenv/python3.5.6/lib/python3.5/site-packages/django/db/models/base.py", line 1137, in full_clean
    self.clean()
  File "/home/travis/build/openwisp/django-ipam/django_ipam/base/models.py", line 57, in clean
    if not ip_network(self.subnet).subnet_of(ip_network(self.master_subnet)):
  File "/opt/python/3.5.6/lib/python3.5/ipaddress.py", line 84, in ip_network
    address)
ValueError: <Subnet: Root 11.0.0.0/24> does not appear to be an IPv4 or IPv6 network
```

2019-04-03 06:43 UTC, atb00ker commented
I'll check it out as soon as possible. :)
Regarding the `segmentation fault`, I've had asked the same on travis's community, they enabled debugging in the repository. However I didn't debug it, did you do it or did it randomly go away? 
( Just asking incase I need to inform something to travis community about it being error in the code or a possible bug in travis. )

2019-04-06 01:12 UTC, nemesifier reviewed
@atb00ker it randomly went away

2019-12-19 10:53 UTC, nemesifier requested changes
there's a validation error in the sample app: https://travis-ci.org/openwisp/django-ipam/jobs/491051689

@atb00ker can you fix it? I think this was ready to merge. It'd be nice to have.

2019-12-20 20:40 UTC, atb00ker commented
The test that was failing randomly went away, I only rebased! 
However, I am concerned about [this](https://github.com/openwisp/django-ipam/pull/73#discussion_r253699450) I haven't fix this and I haven't managed to reproduce it!

2019-12-23 11:16 UTC, nemesifier approved these changes

2019-12-23 11:16 UTC, merged

2019-12-23 11:20 UTC, nemesisdesign commented
Thanks a lot :+1: great work