[qa] Update openwisp-utils-qa-checks migation check
openwisp/django-ipam pull request #87
Opened 2020-01-02 13:16 UTC by waleko

Update `openwisp-utils-qa-checks` (related to openwisp/openwisp-utils#63 for this repo)

2020-01-03 14:03 UTC, atb00ker commented on .travis.yml
> +  - pip install -e git+git://github.com/openwisp/openwisp-utils#egg=openwisp_utils[qa]
Can you please let me know why openwisp-utils 0.3 wouldn't work here? :smile:

2020-01-03 14:14 UTC, atb00ker commented on .travis.yml
> +  - pip install -e git+git://github.com/openwisp/openwisp-utils#egg=openwisp_utils[qa]
Nevermind, got it! :smile:

2020-01-07 17:21 UTC, waleko commented
I fixed most of the stuff, but `checkmigrations` still fails with sample app. Previously, there was just an easy workaround:
https://github.com/openwisp/django-ipam/blob/b4db5413dfe88262cac7d51ebaa210e9b9990480/.travis.yml#L34
Perhaps, we can make an if to skip checkmigrations if `SAMPLE_APP=1`, but maybe it's a bit of a redundancy.

2020-01-08 07:54 UTC, atb00ker reviewed
Can't we try the easy fix again? :smile:

```
if [[ $TRAVIS_PYTHON_VERSION >= 3.5 && $SAMPLE_APP != "1" ]];
    openwisp-utils-qa-checks --migration-path "./django_ipam/migrations/ ./tests/sample_ipam/migrations/"
    --migration-module django_ipam
fi
```

2020-01-08 11:19 UTC, atb00ker approved these changes

2020-01-08 11:21 UTC, atb00ker commented on .travis.yml
> +    if [[ $TRAVIS_PYTHON_VERSION >= 3.5 && $SAMPLE_APP != "1" ]]; then
I just saw travis failing:
I think:
```
TRAVIS_PYTHON_VERSION >= 
```
is not allowed, can you please try `==` to fix it ? 
Use python version 3.6 ! :smile:

2020-01-09 12:11 UTC, nemesifier requested changes

2020-01-09 12:11 UTC, nemesisdesign commented on .travis.yml
> +      openwisp-utils-qa-checks --skip-isort --skip-flake8 --skip-checkmigrations --skip-checkendline --skip-checkcommit --migration-module django_ipam
please use multiline statements for better readability

2020-01-09 12:23 UTC, nemesifier approved these changes

2020-01-09 12:24 UTC, merged